services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_GITHUB_TOKEN: ${REACT_APP_GITHUB_TOKEN}
    image: webpage-portfolio:local
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:80"
